// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: scoreService/proto/score.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreService_proto_score_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_scoreService_proto_score_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_scoreService_proto_score_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Score) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddScoreByUserIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *AddScoreByUserIDResp) Reset() {
	*x = AddScoreByUserIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreService_proto_score_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreByUserIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreByUserIDResp) ProtoMessage() {}

func (x *AddScoreByUserIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_scoreService_proto_score_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreByUserIDResp.ProtoReflect.Descriptor instead.
func (*AddScoreByUserIDResp) Descriptor() ([]byte, []int) {
	return file_scoreService_proto_score_proto_rawDescGZIP(), []int{1}
}

func (x *AddScoreByUserIDResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type AddScoreByUserIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Scores []*Score `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
}

func (x *AddScoreByUserIDReq) Reset() {
	*x = AddScoreByUserIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreService_proto_score_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreByUserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreByUserIDReq) ProtoMessage() {}

func (x *AddScoreByUserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_scoreService_proto_score_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreByUserIDReq.ProtoReflect.Descriptor instead.
func (*AddScoreByUserIDReq) Descriptor() ([]byte, []int) {
	return file_scoreService_proto_score_proto_rawDescGZIP(), []int{2}
}

func (x *AddScoreByUserIDReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AddScoreByUserIDReq) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GetScoreListByUserIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Scores []*Score `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
}

func (x *GetScoreListByUserIDResp) Reset() {
	*x = GetScoreListByUserIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreService_proto_score_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreListByUserIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreListByUserIDResp) ProtoMessage() {}

func (x *GetScoreListByUserIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_scoreService_proto_score_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreListByUserIDResp.ProtoReflect.Descriptor instead.
func (*GetScoreListByUserIDResp) Descriptor() ([]byte, []int) {
	return file_scoreService_proto_score_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoreListByUserIDResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetScoreListByUserIDResp) GetScores() []*Score {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GetScoreListByUserIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Type   uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetScoreListByUserIDReq) Reset() {
	*x = GetScoreListByUserIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreService_proto_score_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreListByUserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreListByUserIDReq) ProtoMessage() {}

func (x *GetScoreListByUserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_scoreService_proto_score_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreListByUserIDReq.ProtoReflect.Descriptor instead.
func (*GetScoreListByUserIDReq) Descriptor() ([]byte, []int) {
	return file_scoreService_proto_score_proto_rawDescGZIP(), []int{4}
}

func (x *GetScoreListByUserIDReq) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetScoreListByUserIDReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_scoreService_proto_score_proto protoreflect.FileDescriptor

var file_scoreService_proto_score_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x31, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x4d, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x22, 0x52, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x06,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x32, 0x9a, 0x01,
	0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x14, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scoreService_proto_score_proto_rawDescOnce sync.Once
	file_scoreService_proto_score_proto_rawDescData = file_scoreService_proto_score_proto_rawDesc
)

func file_scoreService_proto_score_proto_rawDescGZIP() []byte {
	file_scoreService_proto_score_proto_rawDescOnce.Do(func() {
		file_scoreService_proto_score_proto_rawDescData = protoimpl.X.CompressGZIP(file_scoreService_proto_score_proto_rawDescData)
	})
	return file_scoreService_proto_score_proto_rawDescData
}

var file_scoreService_proto_score_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scoreService_proto_score_proto_goTypes = []interface{}{
	(*Score)(nil),                    // 0: Score
	(*AddScoreByUserIDResp)(nil),     // 1: AddScoreByUserIDResp
	(*AddScoreByUserIDReq)(nil),      // 2: AddScoreByUserIDReq
	(*GetScoreListByUserIDResp)(nil), // 3: GetScoreListByUserIDResp
	(*GetScoreListByUserIDReq)(nil),  // 4: GetScoreListByUserIDReq
}
var file_scoreService_proto_score_proto_depIdxs = []int32{
	0, // 0: AddScoreByUserIDReq.scores:type_name -> Score
	0, // 1: GetScoreListByUserIDResp.scores:type_name -> Score
	2, // 2: ScoreService.AddScoreByUserID:input_type -> AddScoreByUserIDReq
	4, // 3: ScoreService.GetScoreListByUser:input_type -> GetScoreListByUserIDReq
	1, // 4: ScoreService.AddScoreByUserID:output_type -> AddScoreByUserIDResp
	3, // 5: ScoreService.GetScoreListByUser:output_type -> GetScoreListByUserIDResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scoreService_proto_score_proto_init() }
func file_scoreService_proto_score_proto_init() {
	if File_scoreService_proto_score_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scoreService_proto_score_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreService_proto_score_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreByUserIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreService_proto_score_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreByUserIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreService_proto_score_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreListByUserIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreService_proto_score_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreListByUserIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scoreService_proto_score_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scoreService_proto_score_proto_goTypes,
		DependencyIndexes: file_scoreService_proto_score_proto_depIdxs,
		MessageInfos:      file_scoreService_proto_score_proto_msgTypes,
	}.Build()
	File_scoreService_proto_score_proto = out.File
	file_scoreService_proto_score_proto_rawDesc = nil
	file_scoreService_proto_score_proto_goTypes = nil
	file_scoreService_proto_score_proto_depIdxs = nil
}
